{{- if .Values.httpProxy.enabled -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "repowise.fullname" . }}
  labels:
    {{- include "repowise.labels" . | nindent 4 }}
spec:
  virtualhost:
    fqdn: {{ .Values.httpProxy.fqdn }}
    {{- if .Values.httpProxy.tls.enabled }}
    tls:
      secretName: {{ .Values.httpProxy.tls.secretName }}
    {{- end }}
  routes:
    - conditions:
        - prefix: /api/
      services:
        - name: {{ include "repowise.fullname" . }}
          port: {{ .Values.service.backendPort }}
    - conditions:
        - prefix: /health
      services:
        - name: {{ include "repowise.fullname" . }}
          port: {{ .Values.service.backendPort }}
    - conditions:
        - prefix: /metrics
      services:
        - name: {{ include "repowise.fullname" . }}
          port: {{ .Values.service.backendPort }}
    - conditions:
        - prefix: /
      services:
        - name: {{ include "repowise.fullname" . }}
          port: {{ .Values.service.frontendPort }}
{{- end }}
